spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://config-server:8888
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: dev
