server:
  port: 8900

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: http://localhost:8000/v3/api-docs/user
      - name: Event Service
        url: http://localhost:8000/v3/api-docs/event