server:
  port: 8086
spring:
  application:
    name: msvc-gateway
  config:
    import: 'configserver:http://localhost:8888'
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: dev
logging:
  level:
    "[org.springframework.web]": TRACE
    "[org.springframework.cloud.gateway]": DEBUG